# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

oneflow-skin    : "air" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

repository               : Duckfloss/KISC.info

locale                   : "en-US"
title                    : "Kalamazoo Immigrant Solidarity Coalition"
title_separator          : "-"
subtitle                 : " " # Displayed in the masthead below the title, use " " for no subtitle
url                      : "https://duckfloss.github.io" # the base hostname & protocol for your site
baseurl                  : /KISC.info # the subpath of your site, e.g. "/blog"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/logo.webp" # Site logo displayed in the masthead
show-popup               : false # set to false if you don't need / want to show a cookie-banner / cdn-usage popup.
                                # Edit the popup itself in the respective /includes file
masthead_title           : "Kalamazoo Immigrant Solidarity Coalition"  # Overrides the website title displayed in the masthead, use " " for no title
sticky-masthead          : true # if true, masthead/navigation bar will stay visible when the user scrolls down.
                                # if false, it will move out of sight when scrolling.
masthead-opacity         : 1 # set to any value between 0 and 1.
                                # 0.8-0.9 is a good recommended starting point. Only relevant if masthead is sticky.
background-image         :  '/assets/images/downtown-kalamazoo.webp' # Remove / out-comment, if you don't want a background image
background-image-mobile  : # '/assets/images/header.webp' # If you want a different (e.g upright) background image for mobile
background-image-overlay : rgba(255, 255, 255, 0.5) # Set overlay for the background image

# Build settings
theme: oneflow-jekyll
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Site Footer.
footer:
  links: # replace the URL's with your own for every link you want to have in your footer.
    - label: "Website"
      icon: "fa fa-globe"
      url: "https://kisc.info"
    - label: "Email"
      icon: "fa fa-envelope"
      url: "mailto: KISC358@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      # url:
    - label: "Facebook"
      icon: "fab fa-facebook"
      # url:
    - label: "GitHub"
      icon: "fab fa-github"
#      url: "https://github.com/perstarke-webdev"
    - label: "Instagram"
      icon: "fab fa-instagram"
#      url: "https://www.instagram.com/per.starke/"
    - label: "YouTube"
      icon: "fab fa-youtube"
#      url: "https://www.youtube.com/channel/UCG2Ndo4IEH8Fa0oIv2FBRMA"
    - label: "Dev"
      icon: "fab fa-dev"
#      url: "https://dev.to/per-starke-642"
#  copyright: "Per Starke Web Development" # Replace with your own
#  creator: # Replace with your own creator name or remove this if you don't want any "created by" in the footer
#      name: "Per Starke Web Development"
#      url: "https://perstarke-webdev.de"



# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style



# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
#  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-gist
#  - jekyll-feed
  - jekyll-include-cache



# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"
